// Node-Express/Kids-Utility-Ng/src/app/math-test/display-question/display-question.component.ts
import { Component, Input, OnInit, Output, EventEmitter, OnChanges } from '@angular/core';

@Component({
  selector: 'app-display-question',
  templateUrl: './display-question.component.html',
  styleUrls: ['./display-question.component.css']
})
export class DisplayQuestionComponent implements OnChanges {

  @Input() testName;
  @Input() minutes;
  @Input() seconds;
  @Input() questionNumber;
  @Input() number1;
  @Input() number2;
  @Input() location;
  @Input() wrongLocation1;
  @Input() wrongLocation2;
  @Input() operator;
  @Input() value;
  @Input() wrongAnswer1;
  @Input() wrongAnswer2;
  
  @Output() onAnswerOptionChange = new EventEmitter();
  @Output() onNextQuestion = new EventEmitter();

  answerOption = '';

  constructor() { }

  ngOnChanges() {   
  }

  answerOptionChange(event) {
    this.answerOption = event.target.value;
    this.onAnswerOptionChange.emit(event.target.value);
  }
  nextQuestion() {
    this.onNextQuestion.emit();
  }

  getOptionValueForRightAnswer() {
    if (this.answerOption == (this.number1 + this.number2).toString())
      return true;
    else
      return false;
  }
  getOptionValueForWrongAnswer1() {
    if (this.answerOption == this.wrongAnswer1.toString())
      return true;
    else
      return false;
  }
  getOptionValueForWrongAnswer2() {
    if (this.answerOption == this.wrongAnswer2.toString())
      return true;
    else
      return false;
  }
}

<div class="row">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-10">
        <div class="card">
            <div class="card-header questionPanel">
                <div class="row">
                    <div class="col-sm-2">
                        <span class="timerDisplay">[ {{minutes}} : {{seconds}} ]</span>
                    </div>
                    <div class="col-sm-7">
                        [Q : {{questionNumber}}] {{number1}} {{operator}} {{number2}} = ___
                    </div>
                    <div class="col-sm-3 nextQuestionBtn">
                        <button type="button" (click)="nextQuestion()" class="btn btn-primary">
                            N . E . X . T
                        </button>
                    </div>
                </div>

            </div>
            <div class="card-body answerPanel">
                <div>
                    <div *ngIf="1==location">
                        <div class="questionOption">
                            <span>
                                <input name="question" 
                                    type="radio" 
                                    value={{value}}
                                    [checked]="getOptionValueForRightAnswer()" 
                                    (change)="answerOptionChange($event)" />
                            </span>
                            <span>
                                {{value}}
                            </span>
                        </div>
                    </div>
                    <div *ngIf="1==wrongLocation1">
                        <div class="questionOption">
                            <span>
                                <input type="radio" 
                                    name="question" 
                                    value={{wrongAnswer1}}
                                    [checked]="getOptionValueForWrongAnswer1()" 
                                    (change)="answerOptionChange($event)" />
                            </span>
                            <span>
                                {{wrongAnswer1}}
                            </span>
                        </div>
                    </div>
                    <div *ngIf="1==wrongLocation2">
                        <div class="questionOption">
                            <span>
                                <input type="radio" 
                                    name="question" 
                                    value={{wrongAnswer2}}
                                    [checked]="getOptionValueForWrongAnswer2()" 
                                    (change)="answerOptionChange($event)" />
                            </span>
                            <span>
                                {{wrongAnswer2}}
                            </span>
                        </div>
                    </div>

                    <div *ngIf="2==location">
                        <div class="questionOption">
                            <span>
                                <input type="radio" name="question" (change)="answerOptionChange($event)"
                                    value={{value}} [checked]="getOptionValueForRightAnswer()" />
                            </span>
                            <span>
                                {{value}}
                            </span>
                        </div>
                    </div>
                    <div *ngIf="2==wrongLocation1">
                        <div class="questionOption">
                            <span>
                                <input type="radio" name="question" (change)="answerOptionChange($event)"
                                    value={{wrongAnswer1}} [checked]="getOptionValueForWrongAnswer1()" />
                            </span>
                            <span>
                                {{wrongAnswer1}}
                            </span>
                        </div>
                    </div>
                    <div *ngIf="2==wrongLocation2">
                        <div class="questionOption">
                            <span>
                                <input type="radio" name="question" (change)="answerOptionChange($event)"
                                    value={{wrongAnswer2}} [checked]="getOptionValueForWrongAnswer2()" />
                            </span>
                            <span>
                                {{wrongAnswer2}}
                            </span>
                        </div>
                    </div>

                    <div *ngIf="3==location">
                        <div class="questionOption">
                            <span>
                                <input type="radio" name="question" (change)="answerOptionChange($event)"
                                    value={{value}} [checked]="getOptionValueForRightAnswer()" />
                            </span>
                            <span>
                                {{value}}
                            </span>
                        </div>
                    </div>
                    <div *ngIf="3==wrongLocation1">
                        <div class="questionOption">
                            <span>
                                <input type="radio" name="question" (change)="answerOptionChange($event)"
                                    value={{wrongAnswer1}} [checked]="getOptionValueForWrongAnswer1()" />
                            </span>
                            <span>
                                {{wrongAnswer1}}
                            </span>
                        </div>
                    </div>
                    <div *ngIf="3==wrongLocation2">
                        <div class="questionOption">
                            <span>
                                <input type="radio" name="question" (change)="answerOptionChange($event)"
                                    value={{wrongAnswer2}} [checked]="getOptionValueForWrongAnswer2()" />
                            </span>
                            <span>
                                {{wrongAnswer2}}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-1">
    </div>
</div>

// Node-Express/React/src/components/math-test/child-components/display-question.js
import React, { Component } from "react";
import { Button, Card } from "react-bootstrap";

export default class DisplayQuestion extends Component {
    constructor(props) {
        super(props);
        this.state = {
            answerOption: '-',
        };

        this.onAnswerOptionChange = this.onAnswerOptionChange.bind(this);
        this.onNextQuestion = this.onNextQuestion.bind(this);
    }

    componentDidMount() {
        
    } 

    onAnswerOptionChange(event) {
        this.setState({
            answerOption: event.target.value
        });
        this.props.parentCallback(event.target.value);
    }

    onNextQuestion() {      
        this.props.parentCallbackNextQuestion();
    }

    render() {
        const { testName, wrongAnswer2, wrongAnswer1, value, operator, wrongLocation1, wrongLocation2, location, minutes, seconds, questionNumber, number1, number2 } = this.props;
        const { answerOption } = this.state;  

        return (
            <div>
                <div className="test-name-header">
                    Test : {testName}
                </div>
                <Card>
                    <Card.Header as="h5" style={{ backgroundColor: "lightskyblue" }}>
                        <div className="row">
                            <div className="col-sm-2 timer">
                                <span>[{minutes} : {seconds}]</span>
                            </div>
                            <div className="col-sm-7">
                                [Q : {questionNumber}] {number1} {operator} {number2} = ___
                            </div>
                            <div className="col-sm-3">
                                <Button variant="success"
                                    onClick={() => this.onNextQuestion()}
                                    size="md">
                                    N.E.X.T
                                </Button>
                            </div>
                        </div>
                    </Card.Header>
                    <Card.Body>
                        <div>
                            {
                                1 == location ? (
                                    <div className="radio radioLeft">
                                        <label>
                                            <span className="optionDisplay">
                                                <input
                                                    type="radio"
                                                    value={value}
                                                    checked={answerOption === value}
                                                    onChange={this.onAnswerOptionChange}
                                                />
                                            </span>
                                            <span>
                                                {value}
                                            </span>
                                        </label>
                                    </div>
                                ) : (
                                    <div>
                                    </div>
                                )
                            }
                            {
                                1 == wrongLocation1 ? (
                                    <div className="radio radioLeft">
                                        <label>
                                            <span className="optionDisplay">
                                                <input
                                                    type="radio"
                                                    value={wrongAnswer1}
                                                    checked={answerOption === wrongAnswer1}
                                                    onChange={this.onAnswerOptionChange}
                                                />
                                            </span>
                                            <span>
                                                {wrongAnswer1}
                                            </span>
                                        </label>
                                    </div>
                                ) : (
                                    <div>
                                    </div>
                                )
                            }
                            {
                                1 == wrongLocation2 ? (
                                    <div className="radio radioLeft">
                                        <label>
                                            <span className="optionDisplay">
                                                <input
                                                    type="radio"
                                                    value={wrongAnswer2}
                                                    checked={answerOption === wrongAnswer2}
                                                    onChange={this.onAnswerOptionChange}
                                                />
                                            </span>
                                            <span>
                                                {wrongAnswer2}
                                            </span>
                                        </label>
                                    </div>
                                ) : (
                                    <div>
                                    </div>
                                )
                            }


                            {
                                2 == location ? (
                                    <div className="radio radioLeft">
                                        <label>
                                            <span className="optionDisplay">
                                                <input
                                                    type="radio"
                                                    value={value}
                                                    checked={answerOption === value}
                                                    onChange={this.onAnswerOptionChange}
                                                />
                                            </span>
                                            <span>
                                                {value}
                                            </span>
                                        </label>
                                    </div>
                                ) : (
                                    <div>
                                    </div>
                                )
                            }
                            {
                                2 == wrongLocation1 ? (
                                    <div className="radio radioLeft">
                                        <label>
                                            <span className="optionDisplay">
                                                <input
                                                    type="radio"
                                                    value={wrongAnswer1}
                                                    checked={answerOption === wrongAnswer1}
                                                    onChange={this.onAnswerOptionChange}
                                                />
                                            </span>
                                            <span>
                                                {wrongAnswer1}
                                            </span>
                                        </label>
                                    </div>
                                ) : (
                                    <div>
                                    </div>
                                )
                            }
                            {
                                2 == wrongLocation2 ? (
                                    <div className="radio radioLeft">
                                        <label>
                                            <span className="optionDisplay">
                                                <input
                                                    type="radio"
                                                    value={wrongAnswer2}
                                                    checked={answerOption === wrongAnswer2}
                                                    onChange={this.onAnswerOptionChange}
                                                />
                                            </span>
                                            <span>
                                                {wrongAnswer2}
                                            </span>
                                        </label>
                                    </div>
                                ) : (
                                    <div>
                                    </div>
                                )
                            }



                            {
                                3 == location ? (
                                    <div className="radio radioLeft">
                                        <label>
                                            <span className="optionDisplay">
                                                <input
                                                    type="radio"
                                                    value={value}
                                                    checked={answerOption === value}
                                                    onChange={this.onAnswerOptionChange}
                                                />
                                            </span>
                                            <span>
                                                {value}
                                            </span>
                                        </label>
                                    </div>
                                ) : (
                                    <div>
                                    </div>
                                )
                            }
                            {
                                3 == wrongLocation1 ? (
                                    <div className="radio radioLeft">
                                        <label>
                                            <span className="optionDisplay">
                                                <input
                                                    type="radio"
                                                    value={wrongAnswer1}
                                                    checked={answerOption === wrongAnswer1}
                                                    onChange={this.onAnswerOptionChange}
                                                />
                                            </span>
                                            <span>
                                                {wrongAnswer1}
                                            </span>
                                        </label>
                                    </div>
                                ) : (
                                    <div>
                                    </div>
                                )
                            }
                            {
                                3 == wrongLocation2 ? (
                                    <div className="radio radioLeft">
                                        <label>
                                            <span className="optionDisplay">
                                                <input
                                                    type="radio"
                                                    value={wrongAnswer2}
                                                    checked={answerOption === wrongAnswer2}
                                                    onChange={this.onAnswerOptionChange}
                                                />
                                            </span>
                                            <span>
                                                {wrongAnswer2}
                                            </span>
                                        </label>
                                    </div>
                                ) : (
                                    <div>
                                    </div>
                                )
                            }









                            <hr />
                            <p></p>
                        </div>
                    </Card.Body>
                </Card>
            </div>
        
        );
    }
}
