// Node-Express/React/src/components/grocery-mgt/my-grocery-component.js
import { useState, useEffect  } from "react";
import './grocery-style.css';

import { FaPlusCircle, FaSave } from "react-icons/fa";

export default function MyGrocery() {

    const [groceryCollection, setGroceryCollection] = useState([]);  
    const [cat, setCat] = useState('');
    const [itemName, setItemName] = useState('');
    const [selected, setSelected] = useState(false);

    const [isDisabled, setIsDisabled] = useState(true);  

    useEffect(() => {
        getGroceryCollection();
    }, []);


    const getCategories = () => {
        return ["Fruit", "Frozen", "Vegitables", "Bakery", "Others"];
    }

    let categoryList = getCategories().length > 0
        && getCategories().map((item, i) => {
            return (
                <option key={i} value={item} >
                    {item}
                </option>
            )
        }, this);

    const onChangeCategory = (event) => {
        console.log(event.target.value);

        if (event.target.value == '' || event.target.value == null) {
            // disable new grocery list item textbox
            setIsDisabled(true);
            setItemName('');
            setCat('');
            return;
        }
        setIsDisabled(false);
        setCat(event.target.value);
    }

    const onChangeItemName = (event) => {
        console.log(event.target.value);
        if (event.target.value == '')
            return;
        else {
            setItemName(event.target.value);
        }
    }

    const getGroceryCollection = () => {
        setGroceryCollection([]);
        fetch('/grocery')
            .then(res => res.json())
            .then(data => {
                setGroceryCollection(data);
                console.log(data);
            }
        );
    }
    const addNewItem = () => {
        
        if (cat === '' || itemName === '') {
            console.log('Error : Item Name is Empty!')
            return;
        }
        console.log(cat + ' : ' + itemName);
        
        var data = {
            cat: cat,
            name: itemName,
            selected: false
        };
        fetch('/grocery/add', {
            method: 'POST',
            body: JSON.stringify(data),
            headers: { 'Content-Type': 'application/json' }
        }).then(res => res.json())
            .then(json => {
                console.log(json);
                getGroceryCollection();
                setItemName('');
                setCat('');
            }
        );
    }

    const saveMyList = () => {

        console.log(groceryCollection);
        // send groceryList to server
        fetch('/grocery/edit', {
            method: 'POST',
            // body: JSON.stringify(groceryCollection),
            body: JSON.stringify(groceryCollection),
            headers: { 'Content-Type': 'application/json' }
        }).then(res => res.json())
            .then(json => {
                console.log(json);
            }
        );
    }

    const updateFieldChanged = index => e => {

        console.log(e.target.value); // Apple
        console.log(e.target.checked); // true, false

        console.log('index: ' + index);
        console.log('property name: ' + e.target.value);
        let newArr = [...groceryCollection]; // copying the old datas array
        newArr[index].selected = e.target.checked; // replace e.target.value with whatever you want to change it to

        setGroceryCollection(newArr);
    }

    let displayFruitGroceryCollection = groceryCollection.map(({ name, cat, selected }, index) => {
        return (
            <span key={index}>
                {
                    cat == "Fruit" && (
                        <span>
                            <li key={index}>
                                <span className="grocery-list-item">
                                    <span>
                                        <input
                                            type="checkbox"
                                            id={name}
                                            name={name}
                                            value={name}
                                            checked={selected}
                                            onChange={updateFieldChanged(index)}                                        
                                        >
                                        </input>
                                        <label>&nbsp;&nbsp;&nbsp;{name}</label>
                                    </span>
                                </span>
                            </li>
                        </span>
                    )
                }
            </span>
        );
    }, this);
    let displayVegitablesGroceryCollection = groceryCollection.map(({ name, cat, selected }, index) => {
        return (
            <span key={index}>
                {
                    cat == "Vegitables" && (
                        <span>
                            <li key={index}>
                                <span className="grocery-list-item">
                                    <span>
                                        <input
                                            type="checkbox"
                                            id={name}
                                            name={name}
                                            value={name}
                                            checked={selected}
                                            onChange={updateFieldChanged(index)}
                                        >
                                        </input>
                                        <label>&nbsp;&nbsp;&nbsp;{name}</label>
                                    </span>
                                </span>
                            </li>
                        </span>
                    )
                }
            </span>
        );
    }, this);
    let displayOthersGroceryCollection = groceryCollection.map(({ name, cat, selected }, index) => {
        return (
            <span key={index}>
                {
                    cat == "Others" && (
                        <span>
                            <li key={index}>
                                <span className="grocery-list-item">
                                    <span>
                                        <input
                                            type="checkbox"
                                            id={name}
                                            name={name}
                                            value={name}
                                            checked={selected}
                                            onChange={updateFieldChanged(index)}
                                        >
                                        </input>
                                        <label>&nbsp;&nbsp;&nbsp;{name}</label>
                                    </span>
                                </span>
                            </li>
                        </span>
                    )
                }
            </span>
        );
    }, this);
    let displayFrozenGroceryCollection = groceryCollection.map(({ name, cat, selected }, index) => {
        return (
            <span key={index}>
                {
                    cat == "Frozen" && (
                        <span>
                            <li key={index}>
                                <span className="grocery-list-item">
                                    <span>
                                        <input
                                            type="checkbox"
                                            id={name}
                                            name={name}
                                            value={name}
                                            checked={selected}
                                            onChange={updateFieldChanged(index)}
                                        >
                                        </input>
                                        <label>&nbsp;&nbsp;&nbsp;{name}</label>
                                    </span>
                                </span>
                            </li>
                        </span>
                    )
                }
            </span>
        );
    }, this);
    let displayBakeryGroceryCollection = groceryCollection.map(({ name, cat, selected }, index) => {
        return (
            <span key={index}>
                {
                    cat == "Bakery" && (
                        <span>
                            <li key={index}>
                                <span className="grocery-list-item">
                                    <span>
                                        <input
                                            type="checkbox"
                                            id={name}
                                            name={name}
                                            value={name}
                                            checked={selected}
                                            onChange={updateFieldChanged(index)}
                                        >
                                        </input>
                                        <label>&nbsp;&nbsp;&nbsp;{name}</label>
                                    </span>
                                </span>
                            </li>
                        </span>
                    )
                }
            </span>
        );
    }, this);
    
    return (
        <div className="row">

            <div >
                <div className="row">
                    <div className="col-sm-4">
                    </div>
                    <div className="col-sm-4">
                        <div className="groceryListHeader">
                            <h3>Grocery List</h3>
                        </div>
                    </div>
                    <div className="col-sm-4">
                    </div>
                </div>                              
                <p></p>
                <div className="groceryListHeaderDetails">              
                    <div className="row">
                        <div className="col-sm-3">
                            <div className="addNewListItem">
                                <form>
                                    <select
                                        className={"form-control"}
                                        style={{height: 40, borderColor: 'green', borderWidth: 3, color: 'blue' }}
                                        id="cat"
                                        value={cat}
                                        onChange={e => onChangeCategory(e)}
                                        name="cat">
                                        <option value=''>
                                            ---select category---
                                        </option>
                                        {categoryList}
                                    </select>
                                    <p></p>
                                    <span className="form-group">
                                        <input
                                            type="text"
                                            placeholder="Item Name"
                                            style={{height: 40, borderColor: 'green', borderWidth: 3, color: 'blue' }}
                                            className={"form-control"}
                                            id="itemName"
                                            value={itemName}
                                            name="itemName"
                                            onChange={e => onChangeItemName(e)}
                                            disabled={isDisabled}
                                        />
                                    </span>
                                </form>
                            </div>
                        </div>                     
                        <div className="col-sm-5 verticalCenter">
                            <button className="btn btn-block "
                                onClick={addNewItem}>                                
                                <FaPlusCircle style={{ color: 'green', fontSize: '50px' }} />
                                &nbsp;&nbsp;<b>Add New Grocery Item Here!</b>
                            </button>
                        </div>
                    </div>
                             
                </div>
            </div>
            <p></p>
            
            <div className="groceryListContainer">
                <div className="row">
                    <div className="col-sm-3">
                        <button className="btn btn-block "
                            onClick={saveMyList}>
                            <FaSave style={{ color: 'green', fontSize: '50px' }} />
                            &nbsp;&nbsp;<b>Save My List!</b>
                        </button>
                    </div>
                    <div className="col-sm-9">
                        <ul >
                            <li>
                                Do Check To Add Item To Your Grocery List
                            </li>
                            <li>
                                Undo Check To Remove Item (Or) Bought Item From Your Grocery List
                            </li>
                        </ul>
                    </div>
                </div>
            
                <p></p>
                <hr />
                <p></p>
                <div className="row">
                    <div className="col-sm-4">
                        <h3><u>Fruits</u></h3>
                        <ul className="grocery-list">
                            {displayFruitGroceryCollection}
                        </ul>
                        <h3><u>Frozen</u></h3>
                        <ul className="grocery-list">
                            {displayFrozenGroceryCollection}
                        </ul>
                    </div>

                    <div className="col-sm-4">
                        <h3><u>Vegitables</u></h3>
                        <ul className="grocery-list">
                            {displayVegitablesGroceryCollection}
                        </ul>
                        <h3><u>Bakery</u></h3>
                        <ul className="grocery-list">
                            {displayBakeryGroceryCollection}
                        </ul>
                    </div>

                    <div className="col-sm-4">
                        <h3><u>Others</u></h3>
                        <ul className="grocery-list">
                            {displayOthersGroceryCollection}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    );
}

// Node-Express/Kids-Utility-Ng/src/app/my-grocery/my-grocery.component.ts
import { Component, OnInit } from '@angular/core';
import {
  AbstractControl,
  FormBuilder,
  FormGroup,
  FormArray,
  FormControl,
  ValidatorFn
} from '@angular/forms';

@Component({
  selector: 'app-my-grocery',
  templateUrl: './my-grocery.component.html',
  styleUrls: ['./my-grocery.component.css']
})
export class MyGroceryComponent implements OnInit {

  apiResponse = '';
  responseColor = '';

  baseServerUrl = 'http://localhost:5000/';
  baseGroceryUrl = 'grocery/';

  groceryCollection: [{name: '', cat: '', selected: false}];
  
  cat: '';
  itemName: '';
  selected: false;
  isDisabled: true;
  
  form: FormGroup;
 
  constructor(private fb: FormBuilder) {
    this.form = this.fb.group({
      checkArray: this.fb.array([])
    })
  }
  ngOnInit(): void {
    this.getGroceryCollection();
  }
  
  onCheckboxChange(e, data) {
    var checkArray: FormArray = this.form.get('checkArray') as FormArray;

    console.log(e.target.value, ' : ', e.target.checked);    

    let index = this.groceryCollection.findIndex(x => x.name === e.target.value);
    index!==-1 && (this.groceryCollection[index].selected = e.target.checked);
  }
  
  getGroceryCollection() {
    fetch(this.baseServerUrl+this.baseGroceryUrl)
      .then(res => res.json())
      .then(data => {        
        console.log(data);
        this.groceryCollection = data;
      }
    );
  };

  saveMyList() {
    console.log(this.groceryCollection);

    this.responseColor = '';
    this.apiResponse = '';

    // send groceryList to server
    fetch(this.baseServerUrl+this.baseGroceryUrl+"edit", {
      method: "POST",
      // body: JSON.stringify(groceryCollection),
      body: JSON.stringify(this.groceryCollection),
      headers: { "Content-Type": "application/json" },
    })
    .then((res) => res.json())
    .then((json) => {
      console.log(json);

      if (json.error) {
        this.responseColor = 'red';
        this.apiResponse = json.error;        
      }
      else {
        this.responseColor = 'green';
        this.apiResponse = json.success;
      
        setTimeout(() => {
          this.onReset();
        }, 3000);
      }
    });
  }
  
  onReset() {
    this.responseColor = '';
    this.apiResponse = '';
  }

  displayOrNot(data, cat) {
    if (data.cat == cat)
      return true;
    else
      return false;
  }
}

<div class="row">
    <div class="col-sm-4">
    </div>
    <div class="col-sm-4">
        <div class="groceryListHeader">
            <h3>Grocery List</h3>
        </div>
    </div>
    <div class="col-sm-4">
    </div>
</div>
<p></p>
<div class="groceryListHeaderDetails">
    <div >
        <div>
            <div class="card-body">
                <form 
                    [formGroup]="formEntry">
                    <div class="form-group">   
                        <div class="row">
                            <div class="col-sm-3 formControl">
                                <select formControlName="Category" class="form-control" (change)="changeCategory($event)">
                                    <option value="">---Select Category---</option>
                                    <option value={{c}} *ngFor="let c of categories">
                                        {{c}}
                                    </option>
                                </select>
                                <p></p>
                                <input type="text" formControlName="ItemName" class="form-control" />
                            </div>
                            <div class="col-sm-6 formControl">
                                <div class="form-group addItemStyle">
                                    <button type="button" 
                                        (click)="addItem()" 
                                        class="btn btn-success">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                    &nbsp;
                                    <span class="addItemTextStyle">Add New Grocery Item Here!</span>
                                    <p></p>
                                    <span *ngIf="addItemApiResponse">
                                        <span [style.color]="responseColor">
                                            <span class="apiResponseStyle">
                                                {{addItemApiResponse}}
                                            </span>
                                        </span>
                                    </span>                                 
                                </div>
                            </div>
                        </div> 
                      
                    </div>
                </form>
            </div>        
        </div>
    </div>
</div>
<p></p>
<div class="groceryListContainer">
    <div class="row">
        <div class="col-sm-3">
            <button class="btn btn-block " 
                (click)="saveMyList()">
                <i class="fa fa-save"></i>
                &nbsp;&nbsp;<b>Save My List!</b>
            </button>
            <div *ngIf="apiResponse">
                <span [style.color]="responseColor">
                    <span class="apiResponseStyle">
                        {{apiResponse}}
                    </span>
                </span>
            </div>
        </div>
        <div class="col-sm-9">
            <ul>
                <li>
                    Do Check To Add Item To Your Grocery List
                </li>
                <li>
                    Undo Check To Remove Item (Or) Bought Item From Your Grocery List
                </li>
            </ul>
        </div>
    </div>
    <p></p>
    <hr />
    <p></p>
    <div class="row">
        <div class="col-sm-12">     
            <form [formGroup]="form"               
                novalidate>
                
                <div class="row">
                    <div class="col-sm-4">
                        <h3><u>Fruits</u></h3>
                        <div *ngFor="let data of groceryCollection; let i=index">
                            <span>
                                <label *ngIf="displayOrNot(data, 'Fruit')" class="itemStyle">
                                    <input type="checkbox" [checked]="data.selected" [value]="data.name"
                                        (change)="onCheckboxChange($event, data)" />
                                    {{data.name}}
                                </label>
                            </span>
                        </div>
                        
                        <p></p>
                        <h3><u>Frozen</u></h3>
                        <div *ngFor="let data of groceryCollection; let i=index">
                            <span>
                                <label *ngIf="displayOrNot(data, 'Frozen')" class="itemStyle">
                                    <input type="checkbox" [checked]="data.selected" [value]="data.name"
                                        (change)="onCheckboxChange($event, data)" />
                                    {{data.name}}
                                </label>
                            </span>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <h3><u>Vegitables</u></h3>
                        <div *ngFor="let data of groceryCollection; let i=index">
                            <span>
                                <label *ngIf="displayOrNot(data, 'Vegitables')" class="itemStyle">
                                    <input type="checkbox" [checked]="data.selected" [value]="data.name"
                                        (change)="onCheckboxChange($event, data)" />
                                    {{data.name}}
                                </label>
                            </span>
                        </div>
                        
                        <p></p>
                        <h3><u>Bakery</u></h3>
                        <div *ngFor="let data of groceryCollection; let i=index">
                            <span>
                                <label *ngIf="displayOrNot(data, 'Bakery')" class="itemStyle">
                                    <input type="checkbox" [checked]="data.selected" [value]="data.name"
                                        (change)="onCheckboxChange($event, data)" />
                                    {{data.name}}
                                </label>
                            </span>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <h3><u>Others</u></h3>
                        <div *ngFor="let data of groceryCollection; let i=index">
                            <span>
                                <label *ngIf="displayOrNot(data, 'Others')" class="itemStyle">
                                    <input type="checkbox" [checked]="data.selected" [value]="data.name"
                                        (change)="onCheckboxChange($event, data)" />
                                    {{data.name}}
                                </label>
                            </span>
                        </div>
                    </div>
                </div>
             
            </form>
         
        </div>
    </div>
</div>
