// Node-Express/Kids-Utility-Ng/src/app/math-test/addition-decimal/addition-decimal.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AbstractControl, FormBuilder, FormGroup, FormControl, Validators } from '@angular/forms';

import { UserService } from '../../services/user.service';
import { LocalDataService } from '../../services/local-data.service';

@Component({
  selector: 'app-addition-decimal',
  templateUrl: './addition-decimal.component.html',
  styleUrls: ['./addition-decimal.component.css']
})
export class AdditionDecimalComponent implements OnInit {

  testName = 'Addition [Decimal]';
  operator = '+';

  parentEmail = '';
  currentUser = '';

  // timer
  timer;
  seconds = 0;
  minutes = 0;
  time = 0;
  isOn = false;
  start = 0;

  // start test
  startTest = false;

  location = 0;
  wrongLocation1 = 0;
  wrongLocation2 = 0;
  questionNumber = 0;
  answerOption = '-';
  number1 = 0.00;
  number2 = 0.00;
  correctAnswer = '';
  wrongAnswer1 = '';
  wrongAnswer2 = '';
  myProgress = [];
  totalCorrect = 0;
  totalWrong = 0;
  displayTestResult = false;
  testResult = {};


  constructor(
    public localDataService: LocalDataService,
    public userService: UserService,
    private formBuilder: FormBuilder,
    public router: Router,
  ) { }
  
  ngOnInit(): void {
    if (!this.userService.isLoggedIn) {
      this.router.navigate(['/home']);
    }
    this.setParentEmail();
    this.setCurrentUser();

    this.onStartTest();
  }

  // set username and parentemail
  setParentEmail() {
    if ((localStorage.getItem('parentEmail')) != "") {
      this.parentEmail = (localStorage.getItem('parentEmail'));
    }
    else {
      this.parentEmail = "";
    }
  }
  setCurrentUser() {
    if ((localStorage.getItem('userName')) != "") {
      this.currentUser = (localStorage.getItem('userName'));
    }
    else {
      this.currentUser = "";
    }
  }
 
  // when user press START TEST button
  // test start
  onStartTest() {
    this.startTest = true;
    this.myProgress = [];
    localStorage.setItem("my-progress", JSON.stringify([]));
    this.getStart();
    this.getMyProgressFromLocalStorage();

    // timer
    // this will start timer when user START test
    this.startTimer();
  }

  // timer
  startTimer() {
    this.seconds = 0;
    this.minutes = 0;
    this.isOn = true;
    this.time = this.time;
    this.start = Date.now() - this.time;
    this.timer = setInterval(() => {
      var seconds_ = this.seconds;
      var minutes_ = this.minutes;
      this.time = Date.now() - this.start;
      this.seconds = (seconds_ == 59) ? (0) : (seconds_ + 1);
      this.minutes = (seconds_ == 59) ? (minutes_ + 1) : (minutes_);
    }, 1000);
  }
  stopTimer() {
    this.isOn = false;
    clearInterval(this.timer)
  }
  resetTimer() {
    this.time = 0;
    this.isOn = false;
  }

  // when user press NEXT question button
  // get new question/right-answer/2 wrong-answers randomly
  getStart() {
    this.getQuestionNumber();
    this.getNumber1();
    this.getNumber2();
    this.getCorrectAnswer();
    this.getWrongAnswer1();
    this.getWrongAnswer2();
  }
  getMyProgressFromLocalStorage() {
    this.myProgress = JSON.parse(localStorage.getItem("my-progress") || "[]");
  }

  getQuestionNumber() {
    this.getRandomLocation();
    var questionNumber = this.questionNumber;
    this.questionNumber = this.questionNumber + 1;
    return this.questionNumber;
  }
  // get random number
  genRand(min, max, decimalPlaces) {
    return (Math.random() * (max - min) + min).toFixed(decimalPlaces) * 1;
  }
  getRandomNumber(min, max) { // min and max included 
    return Math.floor(Math.random() * (max - min + 1) + min)
  }
  getRandomLocation() {
    var location = this.getRandomNumber(1, 3);
    var nums = [1, 2, 3];
    const filter = nums.filter((number) => number != location);
    var wrongLocation1 = filter[0];
    var wrongLocation2 = filter[1];
    console.log(location + ' : ' + wrongLocation1 + ' : ' + wrongLocation2);
    this.location = location;
    this.wrongLocation1 = wrongLocation1;
    this.wrongLocation2 = wrongLocation2;
  }    
  getNumber1 = () => {
    var number1 = this.genRand(1, 99, 2);
    this.number1 = number1;    
    return number1;
  }
  getNumber2 = () => {
    var number2 = this.genRand(1, 99, 2);
    this.number2 = number2;
    return number2;
  }
  getCorrectAnswer = () => {
    this.correctAnswer = ((Number((this.number1.toFixed(2) + this.number2.toFixed(2)))).toFixed(2)).toString();        
    return this.correctAnswer;
  }
  getWrongAnswer1 = () => {    
    this.wrongAnswer1 = ((Number((this.number1.toFixed(2) + this.number2.toFixed(2) + 0.01))).toFixed(2)).toString();    
    return this.wrongAnswer1;
  }
  getWrongAnswer2 = () => {    
    this.wrongAnswer2 = ((Number((this.number1.toFixed(2) + this.number2.toFixed(2) + 0.02))).toFixed(2)).toString();    
    return this.wrongAnswer2;
  }

  // call back from display-question component
  // when user press NEXT question button
  // next question
  onNextQuestion() {
    //store currect question-answer,,, to state and local-storage
    var progressItem = {
      questionNumber: this.questionNumber,
      question: this.number1 + ' + ' + this.number2 + ' = ___',
      myAnswer: this.answerOption,
      correctAnswer: this.getCorrectAnswer(),
      questionResult: this.answerOption == this.getCorrectAnswer().toString() ? "Correct" : "Wrong"
    };
    let currentProgress = this.myProgress;
    currentProgress.push(progressItem);
    this.myProgress = currentProgress;
    localStorage.setItem("my-progress", JSON.stringify(this.myProgress));

    // if last question, then display test result
    if (this.questionNumber == 20) {
      this.displayTestResultNow();

      // stop timer
      this.stopTimer();
      return;
    }

    // continue with next question
    this.answerOption = '-';
    this.getStart();
  }

  // call back from display-question component
  onAnswerOptionChange(userAnswer) {
    console.log(userAnswer);
    this.answerOption = userAnswer;
  }  

  // display test result
  // reset myProgress to [] @ local-storage
  // calculate totalCorrect and totalWrong  
  displayTestResultNow() {
    var testCollection = JSON.parse(localStorage.getItem("my-progress") || "[]");
    if (testCollection) {
      this.displayTestResult = true;
      this.questionNumber = 0;

      this.displayFinalTestResult();
    }
    else {
      this.displayTestResult = false;
    }
  }
  displayFinalTestResult() {
    var testCollection = JSON.parse(localStorage.getItem("my-progress") || "[]");
    if (testCollection) {
      const correctResponse = testCollection.filter(item => item.questionResult === 'Correct');
      const wrongResponse = testCollection.filter(item => item.questionResult === 'Wrong');

      this.totalCorrect = correctResponse.length;
      this.totalWrong = wrongResponse.length;
          

      // post test result to json file
      const testresult = {
        userName: this.currentUser,
        testName: this.testName,
        totalCorrect: correctResponse.length + '',
        totalWrong: wrongResponse.length + '',
      };
          
      console.log(testresult);
      this.testResult = testresult;
    }

    // @last reset local-storage
    this.resetMyProgressAtLocalStorage();
  } 

  // reset current test
  // next test
  resetTest() {
    this.location = 0;
    this.wrongLocation1 = 0;
    this.wrongLocation2 = 0;
    this.questionNumber = 0;
    this.answerOption = '-';
    this.number1 = 0;
    this.number2 = 0;
    this.correctAnswer = '';
    this.wrongAnswer1 = '';
    this.wrongAnswer2 = '';
    this.myProgress = [];
    this.totalCorrect = 0;
    this.totalWrong = 0;
    this.displayTestResult = false;    
  }
  resetMyProgressAtLocalStorage() {
    localStorage.setItem("my-progress", JSON.stringify([]));
  }
}

<div class="row">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-8 test-name-header">
        Test : {{testName}}
    </div>
    <div class="col-sm-2">
    </div>
</div>


<div *ngIf="!displayTestResult">
    <app-display-question (onAnswerOptionChange)="onAnswerOptionChange($event)" (onNextQuestion)="onNextQuestion()"
        [testName]="testName" [minutes]="minutes" [seconds]="seconds" [questionNumber]="questionNumber"
        [number1]="number1" [number2]="number2" [location]="location" [wrongLocation1]="wrongLocation1"
        [wrongLocation2]="wrongLocation2" [operator]="operator" 
        [value]="((number1 + number2).toFixed(2)).toString()"
        [wrongAnswer1]="((number1 + number2 + 0.01).toFixed(2)).toString()" 
        [wrongAnswer2]="((number1 + number2 + 0.02).toFixed(2)).toString()">
    </app-display-question>
</div>

<div *ngIf="displayTestResult" class="row">
    <app-display-test-result [testName]="testName" [minutes]="minutes" [seconds]="seconds" [myProgress]="myProgress"
        [testResult]="testResult" [totalCorrect]="totalCorrect" [totalWrong]="totalWrong" [parentEmail]="parentEmail"
        [userName]="currentUser">
    </app-display-test-result>
</div>

// Node-Express/React/src/components/math-test/addition-decimal-component.js
import React, { Component } from "react";
import { Button, Card } from "react-bootstrap";
import DisplayTestResult from "./child-components/display-test-result";
import DisplayQuestion from "./child-components/display-question";

export default class AdditionDecimal extends Component {
    constructor(props) {
        super(props);

        this.state = {

            parentEmail: '',

            testName: 'Addition - Decimal',

            // timer
            seconds: 0,
            minutes: 0,
            time: 0,
            isOn: false,
            start: 0,

            // start test
            startTest: false,

            location: 0,
            wrongLocation1: 0,
            wrongLocation2: 0,

            questionNumber: 0,
            answerOption: '-',
            number1: 0,
            number2: 0,
            correctAnswer: 0,
            wrongAnswer1: 0,
            wrongAnswer2: 0,

            myProgress: [],
            totalCorrect: 0,
            totalWrong: 0,
            displayTestResult: false
        };

        this.startTest = this.onStartTest.bind(this);
        this.onAnswerOptionChange = this.onAnswerOptionChange.bind(this);
        this.onNextQuestion = this.onNextQuestion.bind(this);
        this.nextText = this.onNextTest.bind(this);

        // timer
        this.startTimer = this.startTimer.bind(this)
        this.stopTimer = this.stopTimer.bind(this)
        this.resetTimer = this.resetTimer.bind(this)
    }

    componentDidMount() {
        const user = this.getCurrentUser();
        if (!user) {
            this.props.history.push('/login');
            window.location.reload();
        }
        this.setParentEmail();
    }
    getCurrentUser() {
        return JSON.parse(localStorage.getItem('userName'));
    }
    setParentEmail() {
        this.setState({
            parentEmail: JSON.parse(localStorage.getItem('parentEmail'))
        });
    }


    onStartTest() {
        this.setState({
            startTest: true,
            myProgress: []
        });
        localStorage.setItem("my-progress", []);

        this.getStart();
        this.getMyProgressFromLocalStorage();

        this.startTimer();
    }

    // timer
    startTimer() {
        this.setState({
            seconds: 0,
            minutes: 0,
            isOn: true,
            time: this.state.time,
            start: Date.now() - this.state.time
        })
        this.timer = setInterval(() => {
            var seconds_ = this.state.seconds;
            var minutes_ = this.state.minutes;
            this.setState({
                time: Date.now() - this.state.start,
                seconds: (seconds_ == 59) ? (0) : (seconds_ + 1),
                minutes: (seconds_ == 59) ? (minutes_ + 1) : (minutes_),
            })
        }, 1000);
    }
    stopTimer() {
        this.setState({ isOn: false })
        clearInterval(this.timer)
    }
    resetTimer() {
        this.setState({ time: 0, isOn: false })
    }

    // next test
    resetTest() {
        this.setState({
            location: 0,
            wrongLocation1: 0,
            wrongLocation2: 0,

            questionNumber: 0,
            answerOption: '-',
            number1: 0,
            number2: 0,
            correctAnswer: 0,
            wrongAnswer1: 0,
            wrongAnswer2: 0,

            myProgress: [],
            totalCorrect: 0,
            totalWrong: 0,
            displayTestResult: false
        });
        this.getStart();
        this.getMyProgressFromLocalStorage();
    }

    getStart() {
        this.getQuestionNumber();
        this.getNumber1();
        this.getNumber2();
        this.getCorrectAnswer();
        this.getWrongAnswer1();
        this.getWrongAnswer2();
    }
    getMyProgressFromLocalStorage() {
        this.setState({
            myProgress: JSON.parse(localStorage.getItem("my-progress") || "[]")
        });
    }

    onAnswerOptionChange(childData) {
        this.setState({
            answerOption: childData
        });
    }

    // get random number
    genRand(min, max, decimalPlaces) {
        return (Math.random() * (max - min) + min).toFixed(decimalPlaces) * 1;
    }

    getRandomNumber(min, max) { // min and max included 
        return Math.floor(Math.random() * (max - min + 1) + min)
    }
    getRandomLocation() {
        var location = this.getRandomNumber(1, 3);
        var nums = [1, 2, 3];
        const filter = nums.filter((number) => number != location);
        var wrongLocation1 = filter[0];
        var wrongLocation2 = filter[1];
        console.log(location + ' : ' + wrongLocation1 + ' : ' + wrongLocation2);
        this.setState({
            location: location,
            wrongLocation1: wrongLocation1,
            wrongLocation2: wrongLocation2
        });
    }

    getQuestionNumber() {
        this.getRandomLocation();

        var questionNumber = this.state.questionNumber;
        this.setState({
            questionNumber: questionNumber + 1
        });
        return this.state.questionNumber;
    }
    getNumber1 = () => {
        var number1 = this.genRand(1, 99, 2);
        this.setState({
            number1: number1
        });
        return number1;
    }
    getNumber2 = () => {
        var number2 = this.genRand(1, 99, 2);
        this.setState({
            number2: number2
        });
        return number2;
    }

    getCorrectAnswer = () => {
        var number1 = this.state.number1;
        var number2 = this.state.number2;
        var correctAnswer = (number1 + number2).toFixed(2);      
        this.setState({
            correctAnswer: correctAnswer
        });
        return correctAnswer;
    }
    getWrongAnswer1 = () => {        
        var number1 = this.state.number1;
        var number2 = this.state.number2;
        var wrongAnswer1 = (number1 + number2 + 0.01).toFixed(2);      
        this.setState({
            wrongAnswer1: wrongAnswer1
        });
        return wrongAnswer1;
    }
    getWrongAnswer2 = () => {
        var number1 = this.state.number1;
        var number2 = this.state.number2;
        var wrongAnswer2 = (number1 + number2 - 0.01).toFixed(2);
        this.setState({
            wrongAnswer2: wrongAnswer2
        });
        return wrongAnswer2;
    }

    // display test result
    // call child component
    displayTestResult() {
        var testCollection = JSON.parse(localStorage.getItem("my-progress") || "[]");
        if (testCollection) {
            this.setState({
                displayTestResult: true,
                questionNumber: 0
            });
        }
        else {
            this.setState({
                displayTestResult: false
            });
        }
    }

    // next question
    onNextQuestion() {
        //store currect question-answer,,, to state and local-storage
        var progressItem = {
            questionNumber: this.state.questionNumber,
            question: this.state.number1 + ' + ' + this.state.number2 + ' = ___',
            myAnswer: this.state.answerOption,
            correctAnswer: this.getCorrectAnswer(),
            questionResult: this.state.answerOption == this.getCorrectAnswer() ? "Correct" : "Wrong"
        };
        let currentProgress = this.state.myProgress;
        currentProgress.push(progressItem);
        this.setState({
            myProgress: currentProgress
        });
        localStorage.setItem("my-progress", JSON.stringify(this.state.myProgress));

        // if last question, then display test result
        if (this.state.questionNumber == 20) {
            this.displayTestResult();

            // stop timer
            this.stopTimer();
            return;
        }

        // continue with next question
        this.getStart();
    }

    onNextTest() {
        this.resetTest();
    }

    render() {
        const { testName, parentEmail, startTest, seconds, minutes, wrongLocation1, wrongLocation2, location, myProgress, displayTestResult, totalCorrect, totalWrong, questionNumber, number1, number2, answerOption, correctAnswer, wrongAnswer1, wrongAnswer2 } = this.state;

        return (
            <div>
                {startTest ? (
                    <div className="row">
                        <div className="col-sm-1">
                        </div>

                        {displayTestResult ? (
                            <div className="col-sm-10">
                                <DisplayTestResult
                                    testName={testName}
                                    minutes={minutes}
                                    seconds={seconds}
                                    parentEmail={parentEmail}
                                    myProgress={myProgress}
                                />
                            </div>
                        ) : (
                                <div className="col-sm-10" >
                                    <div>
                                        <DisplayQuestion
                                            parentCallback={this.onAnswerOptionChange}
                                            parentCallbackNextQuestion={this.onNextQuestion}
                                            testName={testName}
                                            minutes={minutes}
                                            seconds={seconds}
                                            questionNumber={questionNumber}
                                            number1={number1}
                                            number2={number2}
                                            location={location}
                                            wrongLocation1={wrongLocation1}
                                            wrongLocation2={wrongLocation2}
                                            operator={'+'}
                                            value={((number1 + number2).toFixed(2)).toString()}
                                            wrongAnswer1={((number1 + number2 + 0.01).toFixed(2)).toString()}
                                            wrongAnswer2={((number1 + number2 - 0.01).toFixed(2)).toString()}
                                        />
                                    </div>
                                </div >
                        )}

                        <div className="col-sm-1" >
                        </div>
                    </div>                    
                ) : (
                    <div className="row">
                        <div>
                            <h4><b>{testName}</b></h4>
                            <p></p>
                            <span>
                                <Button variant="info"
                                    onClick={() => this.onStartTest()}
                                    size="md">
                                    S.T.A.R.T &nbsp;&nbsp; T.E.S.T
                                </Button>
                            </span>
                        </div>
                    </div>
                )}
            </div>
        );
    }
}
