// Node-Express/Kids-Utility-Ng/src/app/event-mgt/create-event/create-event.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AbstractControl, FormBuilder, FormGroup, FormControl, Validators } from '@angular/forms';

import { UserService } from '../../services/user.service';
import { LocalDataService } from '../../services/local-data.service';

@Component({
  selector: 'app-create-event',
  templateUrl: './create-event.component.html',
  styleUrls: ['./create-event.component.css']
})
export class CreateEventComponent implements OnInit {

  responseColor = '';
  apiResponse = '';

  eventTimeValue = { hour: 13, minute: 30 };
  meridian = true;

  form: FormGroup = new FormGroup({
    eventDateValue: new FormControl(''),
    eventTimeValue: new FormControl(''),
    eventTitle: new FormControl(''),
    eventDesc: new FormControl(''),
  });
  submitted = false;
 
  currentUser = '';
  
  constructor(
    public localDataService: LocalDataService,
    public userService: UserService,
    private formBuilder: FormBuilder,
    public router: Router,
  ) { }

  setCurrentUser() {
    if ((localStorage.getItem('userName')) != "") {
      this.currentUser = (localStorage.getItem('userName'));
    }
    else {
      this.currentUser = "";
    }
  }
  
  ngOnInit(): void {
    if (!this.userService.isLoggedIn) {
      this.router.navigate(['/home']);
    }
   
    this.setCurrentUser();

    this.form = this.formBuilder.group(
      {
        eventDateValue: [
          '',
          [
            Validators.required,
          ]
        ],
        eventTimeValue: [
          '',
          [
            Validators.required,
          ]
        ],
        eventTitle: [
          '',
          [
            Validators.required,
          ]
        ],
        eventDesc: [
          '',
          [
            Validators.required,
          ]
        ],
      
      },
    );
  }

    get f(): { [key: string]: AbstractControl } {
    return this.form.controls;
    }
  
  onSubmit(): void {
    this.responseColor = '';
    this.apiResponse = '';
    this.submitted = true;

    if (this.form.invalid) {
      // return;
    }
    console.log(this.form.value);


    var eventDate_ = this.form.value["eventDateValue"];
    var edate = new Date(eventDate_);
    edate.setHours(this.eventTimeValue.hour - 5, this.eventTimeValue.minute, 0);   // Set hours, minutes and seconds
    // console.log(edate.toUTCString()+"-0600 (Central Standard Time)");

    var eventModel = {
      id: this.localDataService.getGUID(),
      userName: this.currentUser,
      eventDate: edate.toUTCString() + "-0600 (Central Standard Time)",
      eventTitle: this.form.value["eventTitle"],
      eventDesc: this.form.value["eventDesc"],
    }

    console.log(eventModel);

    // api call
    fetch(this.localDataService.getServerUrl()+this.localDataService.getEventServiceUrl()+'create', {
      method: 'POST',
      body: JSON.stringify(eventModel),
      headers: { 'Content-Type': 'application/json' }
    }).then(res => res.json())
      .then(json => {
        console.log(json);
        if (json.error) {
          this.responseColor = 'red';
          this.apiResponse = json.error;
        }
        else {
          this.responseColor = 'green';
          this.apiResponse = json.message;

          this.onReset();

          // redirect to view-event
          setTimeout(() => {
            this.apiResponse = '';
            this.responseColor = '';
          }, 2000);
        }
      }
      );
  }

  onReset(): void {
    this.submitted = false;
    this.form.reset();
  }

}

<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h3>Create Your Event !</h3>
                    <p></p>
                    <div *ngIf="apiResponse">
                        <span [style.color]="responseColor" 
                            class="apiResponse">
                            {{apiResponse}}
                        </span>
                    </div>
                </div>
                <div class="card-body">
                    <form [formGroup]="form" 
                        (ngSubmit)="onSubmit()">
                        <div class="row">
                            <div class="col-md-6 mx-auto">
                                <div class="form-group">
                                    <label>Event-Date</label>
                                    <input [bsConfig]="{ isAnimated: true, dateInputFormat: 'YYYY-MM-DD' }" type="text" placeholder="Start Run Time"
                                        bsDatepicker formControlName="eventDateValue" class="form-control eventDate"
                                        [ngClass]="{ 'is-invalid': submitted && f['eventDateValue'].errors }" />
                                    <div *ngIf="submitted && f['eventDateValue'].errors" class="invalid-feedback">
                                        <div *ngIf="f['eventDateValue'].errors['required']">
                                            Event Date is required
                                        </div>
                                    </div>
                                    <p></p>
                                    <label>Event-Time</label>
                                    <ngb-timepicker class="form-control" formControlName="eventTimeValue"
                                        [ngClass]="{ 'is-invalid': submitted && f['eventTimeValue'].errors }" [(ngModel)]="eventTimeValue"
                                        [meridian]="meridian">
                                    </ngb-timepicker>
                                    <div *ngIf="submitted && f['eventTimeValue'].errors" class="invalid-feedback">
                                        <div *ngIf="f['eventTimeValue'].errors['required']">Event Time is required</div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mx-auto">
                                <div class="form-group">
                                    <label>Event-Title</label>
                                    <input type="text" 
                                        formControlName="eventTitle" class="form-control"
                                        [ngClass]="{ 'is-invalid': submitted && f['eventTitle'].errors }" />
                                    <div *ngIf="submitted && f['eventTitle'].errors" class="invalid-feedback">
                                        <div *ngIf="f['eventTitle'].errors['required']">Event Title is required</div>
                                    </div>
                                </div>
                                <p></p>
                                <div class="form-group">
                                    <label>Event-Desc</label>
                                    <input type="text" formControlName="eventDesc" class="form-control"
                                        [ngClass]="{ 'is-invalid': submitted && f['eventDesc'].errors }" />
                                    <div *ngIf="submitted && f['eventDesc'].errors" class="invalid-feedback">
                                        <div *ngIf="f['eventDesc'].errors['required']">Event Desc is required</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <p></p>
                        <hr />
                        <p></p>
                        <div class="form-group">
                            <button type="submit" 
                                class="btn btn-success">
                                Create Event
                            </button>
                            &nbsp;&nbsp;
                            <button type="button" 
                                (click)="onReset()"
                                class="btn btn-primary float-right">
                                Reset
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

// Node-Express/React/src/components/event-mgt/create-event-component.js
import React, { Component, useState, useEffect } from "react";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import moment from "moment";
import { Card, Table } from "react-bootstrap";
import { useHistory } from 'react-router-dom'

const CreateEvent = () => {
    const history = useHistory();

    const [eventDate, setEventDate] = useState(new Date());
    const [eventTitle, setEventTitle] = useState('');
    const [eventDesc, setEventDesc] = useState('');
    const [apiResponse, setApiResponse] = useState('');

    const getGUID = () => {
        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
            var r = Math.random() * 16 | 0, v = c === 'x' ? r : (r & 0x3 | 0x8);
            return v.toString(16);
        });
    }

    useEffect(() => {
        const user = getCurrentUser();
        if (!user) {
            history.push('login');
            return;
        }
        
        localStorage.removeItem("selectedEvent");
    }, []);


    const handleEventDate = (date) => {
        var timelagging = 6; // 5 or 6
        setEventDate(date);

        var currentDateTime = new Date();
        var cdt = new Date(currentDateTime.getTime() - ((1 * 60 * 60 * 1000) * timelagging));
        currentDateTime = cdt;
   
        var d = (date - currentDateTime);     
        var Difference_In_Days = (d / (1000 * 3600 * 24)).toFixed(0);
    };
    const handleEventTitle = (event) => {
        setEventTitle(event.target.value);
    };
    const handleEventDesc = (event) => {
        setEventDesc(event.target.value);
    };

    const getCurrentUser = () => {
        return JSON.parse(localStorage.getItem('userName'));
    }

    const handleSubmit = (evt) => {
        evt.preventDefault();       

        // prepare data for api call        
        var data = {
            id: getGUID(),
            userName: getCurrentUser(),
            eventDate: eventDate.toString(),
            eventTitle: eventTitle,
            eventDesc: eventDesc
        };

        // api call
        fetch('/event/create', {
            method: 'POST',
            body: JSON.stringify(data),
            headers: { 'Content-Type': 'application/json' }
        }).then(res => res.json())
            .then(json => {
                console.log(json);
                if (json.error) {
                    setApiResponse(json.error);
                }
                else {
                    setApiResponse('Success!');
                    setEventDesc('');
                    setEventTitle('');
                    setEventDate('');

                    // redirect to view-event
                    setTimeout(() => {
                        history.push('view-event');
                    }, 2000);
                }
            }
        );
    }

    return (
        <div>
            <div className="row">
                <div className="col-sm-3">
                </div>
                <div className="col-sm-6">
                    <form onSubmit={handleSubmit} noValidate>
                        <Card >
                            <Card.Header>
                                <div style={{ marginBottom: 30 }}>
                                    <h3 >Create Your Event !</h3>
                                    <p></p>
                                    {apiResponse == 'Success!' ? (
                                        <span className="createEventSuccess">{apiResponse}</span>
                                    ): (
                                            <span className="createEventError">{apiResponse}</span>
                                    )}                                    
                                </div>
                            </Card.Header>
                            <Card.Body>
                                <div className="form-group">
                                    <Card.Title>Event Title</Card.Title>
                                    <Card.Text>
                                        <input
                                            type="text"
                                            className="form-control"
                                            name="eventTitle"
                                            value={eventTitle}
                                            id="eventTitle"
                                            onChange={e => handleEventTitle(e)}
                                        />
                                    </Card.Text>                                
                                </div>
                                <p></p>
                                <div className="form-group">
                                    <Card.Title>Event Description</Card.Title>
                                    <Card.Text>
                                        <input
                                            type="text"
                                            className="form-control"
                                            name="eventDesc"
                                            value={eventDesc}
                                            id="eventDesc"
                                            onChange={e => handleEventDesc(e)}
                                        />
                                    </Card.Text>
                                </div>
                                <p></p>
                                <div className="form-group">
                                    <Card.Title>Event Date/Time</Card.Title>
                                    <div>
                                        <DatePicker
                                            selected={eventDate}
                                            onChange={date => handleEventDate(date)}
                                            showTimeSelect
                                            dateFormat="Pp"
                                        />
                                    </div>
                                </div>
                                <p></p>
                                <hr />
                                <div className="row">
                                    <div className="col-sm-5">
                                        <button
                                            type="submit"
                                            className="btn btn-block btn-success">
                                            <h5>Create Event</h5>
                                        </button>
                                    </div>
                                </div>
                            </Card.Body>
                        </Card>
                    </form>
                </div>           
            </div>         
        </div>
    );
};

export default CreateEvent;
